/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Plans: () => import('#controllers/plans_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
